**Домашнее задание 2**

Во втором дз предлагается поработать с достаточно большим датасетом, [описание](https://archive.ics.uci.edu/ml/datasets/bank+marketing). Решите предложенные задания с использованием модуля Pandas (NumPy, разумеется, тоже разрешен).

Использование условий и циклов крайне нежелательно (списковые включения это тоже цикл!), за это будут снижаться баллы.
Все задания равноценны (кроме нулевой).
В каждой задаче постарайтесь придумать несколько решений. Решением должен быть Jupyter notebook / ссылка на Colab

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = 'https://raw.githubusercontent.com/Sketchjar/MachineLearningHD/main/bank_marketing_dataset.csv'

df = pd.read_csv(url)

0. Каков размер датасета? Выведите первые 2 строки. Выведите две случайные строки. Какие типы колонок в датафрейме?

In [ ]:
print(df.shape)           #выводим размер датасета
df.head(2)                #выводим первые 2 строчки

(41188, 21)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df.sample(2)              #выводим 2 случайные строчки

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome
23931,53,self-employed,married,university.degree,no,yes,no,cellular,aug,fri,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,no
15329,31,self-employed,single,university.degree,no,yes,no,cellular,jul,fri,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.957,5228.1,no

In [ ]:
df.dtypes                 #выводим типы данных столбцов

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
outcome            object
dtype: object

1. Выведите основные статистические показатели для числовых признаков – количество значений, среднее, стандартное отклонение, min/max, медиану, верхнюю и нижнюю квартиль.

In [ ]:
numberdf = df.select_dtypes(include='number')
numberdf.nunique()                #количество уникальных значений

age                 78
duration          1544
campaign            42
pdays               27
previous             8
emp.var.rate        10
cons.price.idx      26
cons.conf.idx       26
euribor3m          316
nr.employed         11
dtype: int64

In [ ]:
numberdf.count()                  #количество значений

age               41188
duration          41188
campaign          41188
pdays             41188
previous          41188
emp.var.rate      41188
cons.price.idx    41188
cons.conf.idx     41188
euribor3m         41188
nr.employed       41188
dtype: int64

In [ ]:
numberdf.mean()                   #среднее

age                 40.024060
duration           258.285010
campaign             2.567593
pdays              962.475454
previous             0.172963
emp.var.rate         0.081886
cons.price.idx      93.575664
cons.conf.idx      -40.502600
euribor3m            3.621291
nr.employed       5167.035911
dtype: float64

In [ ]:
numberdf.std( )                   #стандартное отклонение

age                10.421250
duration          259.279249
campaign            2.770014
pdays             186.910907
previous            0.494901
emp.var.rate        1.570960
cons.price.idx      0.578840
cons.conf.idx       4.628198
euribor3m           1.734447
nr.employed        72.251528
dtype: float64

In [ ]:
numberdf.min()                    #минимальное значение

age                 17.000
duration             0.000
campaign             1.000
pdays                0.000
previous             0.000
emp.var.rate        -3.400
cons.price.idx      92.201
cons.conf.idx      -50.800
euribor3m            0.634
nr.employed       4963.600
dtype: float64

In [ ]:
numberdf.max()                    #максимальное значение

age                 98.000
duration          4918.000
campaign            56.000
pdays              999.000
previous             7.000
emp.var.rate         1.400
cons.price.idx      94.767
cons.conf.idx      -26.900
euribor3m            5.045
nr.employed       5228.100
dtype: float64

In [ ]:
numberdf.median()                 #медиана

age                 38.000
duration           180.000
campaign             2.000
pdays              999.000
previous             0.000
emp.var.rate         1.100
cons.price.idx      93.749
cons.conf.idx      -41.800
euribor3m            4.857
nr.employed       5191.000
dtype: float64

In [ ]:
numberdf.quantile([0.25, 0.75])   #верхний и нижний квартиль

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
0.25,32.0,102.0,1.0,999.0,0.0,-1.8,93.075,-42.7,1.344,5099.1
0.75,47.0,319.0,3.0,999.0,0.0,1.4,93.994,-36.4,4.961,5228.1

2. Выведите число значений, уникальных значений, самое частое из значений (и его частоту) для всех остальных признаков.

In [ ]:
notnumberdf = df.select_dtypes(exclude='number')
notnumberdf.count()            #число значений

job            41188
marital        41188
education      41188
default        41188
housing        41188
loan           41188
contact        41188
month          41188
day_of_week    41188
poutcome       41188
outcome        41188
dtype: int64

In [ ]:
notnumberdf.nunique()          #число уникальных значений

job            12
marital         4
education       8
default         3
housing         3
loan            3
contact         2
month          10
day_of_week     5
poutcome        3
outcome         2
dtype: int64

In [ ]:
notnumberdf.mode()            #самые частые значения по столбцам

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,outcome
0,admin.,married,university.degree,no,yes,no,cellular,may,thu,nonexistent,no

In [ ]:
print('Количество самого частого значения в колонке job ', notnumberdf['job'].value_counts()[0])
print('Количество самого частого значения в колонке marital ', notnumberdf['marital'].value_counts()[0])
print('Количество самого частого значения в колонке education ', notnumberdf['education'].value_counts()[0])
print('Количество самого частого значения в колонке default ', notnumberdf['default'].value_counts()[0])
print('Количество самого частого значения в колонке housing ', notnumberdf['housing'].value_counts()[0])
print('Количество самого частого значения в колонке loan ', notnumberdf['loan'].value_counts()[0])
print('Количество самого частого значения в колонке contact ', notnumberdf['contact'].value_counts()[0])
print('Количество самого частого значения в колонке month ', notnumberdf['month'].value_counts()[0])
print('Количество самого частого значения в колонке day_of_week ', notnumberdf['day_of_week'].value_counts()[0])
print('Количество самого частого значения в колонке poutcome ', notnumberdf['poutcome'].value_counts()[0])
print('Количество самого частого значения в колонке outcome ', notnumberdf['outcome'].value_counts()[0])

Количество самого частого значения в колонке job  10422
Количество самого частого значения в колонке marital  24928
Количество самого частого значения в колонке education  12168
Количество самого частого значения в колонке default  32588
Количество самого частого значения в колонке housing  21576
Количество самого частого значения в колонке loan  33950
Количество самого частого значения в колонке contact  26144
Количество самого частого значения в колонке month  13769
Количество самого частого значения в колонке day_of_week  8623
Количество самого частого значения в колонке poutcome  35563
Количество самого частого значения в колонке outcome  36548

3. Сколько в выборке неграмотных людей? А безработных? Какой процент в выборке разведенных людей?

In [ ]:
df['education'].value_counts()['illiterate']  #количество неграмотных людей

18

In [ ]:
df['job'].value_counts()['unemployed']        #количество безработных

1014

In [ ]:
df['marital'].value_counts()['divorced'] / df['marital'].count() * 100      #процент разведенных людей

11.197436146450421

4. Вставьте вместо пропусков в колонку job самое частое значение в этой колонке

In [ ]:
df['job'] = df['job'].fillna(df['job'].mode())                                  #заполняем вместо NaN самой частой работой

5. Сравните средний возраст женатых и одиноких людей

In [ ]:
print('Средний возраст женатых людей - ', df['age'][df['marital'] == 'married'].mean())   #смотрим средний возраст людей, статус которых женаты
print('Средний возраст одиноких людей - ', df['age'][df['marital'] == 'single'].mean())   #смотрим средний возраст людей, статус которых одиноки

Средний возраст женатых людей -  42.30716463414634
Средний возраст одиноких людей -  33.15871369294606

6. Добавьте в датафрейм признак "логарифм длины последнего звонка". Для некоторых моделей машинного обучения могут быть полезны подобные признаки.

In [ ]:
df['log_last_call'] = np.log2(df['duration'])                                   #просто создаем новую колонку с логарифмом от длины звонка

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

7. Выведите часть датасета, в которой будут все люди с минимальным в выборке возрастом, согласившиеся на срочный вклад

In [ ]:
low_age_df = df[df['age'] == df['age'].min()]                                   #берем всех людей с нимимальным возрастом
low_age_df = low_age_df[low_age_df['outcome'] == 'yes']                         #оставляем только тех из них, кто согласился на вклад
low_age_df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome,log_last_call
37579,17,student,single,basic.9y,no,unknown,unknown,cellular,aug,fri,...,999,1,failure,-2.9,92.201,-31.4,0.869,5076.2,yes,8.960002
38274,17,student,single,unknown,no,no,yes,cellular,oct,tue,...,2,2,success,-3.4,92.431,-26.9,0.742,5017.5,yes,9.807355

8. Создайте новый датафрейм, в который войдут 10 самых возрастных клиентов, которые работают. В нем строки должны быть отсортированы по возрасту в порядке убывания, а индексом должны являться числа от 0 до 9 включительно. Оставьте в новом датафрейме (помимо индекса) только колонки age, marital education, housing, loan

In [ ]:
high_age_df = df[(df['job'] != 'unknown') & (df['job'] != 'unemployed') & (df['job'] != 'retired') & (df['job'] != 'student')]  #удаляем всех безработных
high_age_df = high_age_df.sort_values(by=['age'], ascending=False).head(10)             #сортируем по возрасту, и отбираем 10 самых возрастных
high_age_df.reset_index(drop = True, inplace = True )                                   #удаляем старые индексы, и добавляем новые
high_age_df = high_age_df[['age', 'marital', 'education', 'housing', 'loan']]           #оставляем только нужные колонки
high_age_df

   age   marital education  housing     loan
0   85   married  basic.4y       no       no
1   85   married  basic.4y      yes       no
2   85   married  basic.4y       no       no
3   85   married  basic.4y      yes       no
4   85  divorced  basic.4y      yes       no
5   83  divorced  basic.4y      yes      yes
6   83  divorced  basic.4y      yes       no
7   82  divorced  basic.4y       no       no
8   82   married  basic.4y       no       no
9   82  divorced  basic.4y  unknown  unknown

9. Создайте столбец с датой контакта. Дата должна соответствовать информации из столбцов month и day_of_week и относиться к 2021 году (в этом задании может быть, разумеется, много верных ответов, выведите любой)

In [ ]:
df['date'] = df['day_of_week'] + '-' + df['month'] + '-2021'              #создаем колонку в формате "mon-may-2021"
df['date'].head()

0    mon-may-2021
1    mon-may-2021
2    mon-may-2021
3    mon-may-2021
4    mon-may-2021
Name: date, dtype: object

10. Какие два столбца исходного датафрейма наиболее скоррелированные?

In [ ]:
df_corr = df.corr()                                                       #создаем новый дф, заполненный коррелируемыми значениями
np.fill_diagonal(df_corr.values, np.nan)                                  #удаляем значения по диагонали, так как они всегда равны 1 и будут нам мешать

maximum = df_corr.max().max()                                             #находим значение максимальной корреляции

column = df_corr.eq(maximum).any()                                        #методом eq заполняем дф булевыми значениями, которые отражают, есть ли в данном столбце нужный нам элемент, затем методом any(), мы находим все значения True
itog_column = column[column].index[0]                                     #берем 1-й столбец, где мы находим true

row = df_corr.eq(maximum).any(axis=1)                                     #аналогично столбцам, только для строк
itog_row = row[row].index[1]

print("Столбец с максимальным значением корреляции: ", itog_column)
print("Строка с максимальным значением корреляции: ", itog_row)

Столбец с максимальным значением корреляции:  emp.var.rate
Строка с максимальным значением корреляции:  euribor3m

<ipython-input-474-26486d5e47db>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_corr = df.corr()                                                       #создаем новый дф, заполненный коррелируемыми значениями